bucket_name = 'abherbs-resources'
thumbdir = '.thumbnails'
storagedir = '/home/adrian/Dev/Storage/photos/'
plantsdir = '/home/adrian/Dev/Plants/'
observationsdir = '/home/adrian/Dev/Observations/'
sources = 'sources.txt'
extension = '.webp'
extension_txt = '.txt'
certificate_firebase = '/home/adrian/Dev/keystore/abherbs-backend-firebase-adminsdk-l5787-69082c19ae.json'
databaseURL = 'https://abherbs-backend.firebaseio.com'

apgiv_names = {
    'Amborellales': 'Superregnum/Regnum/Cladus/Cladus/Ordo',
    'Austrobaileyales': 'Superregnum/Regnum/Cladus/Cladus/Ordo',
    'Nymphaeales': 'Superregnum/Regnum/Cladus/Cladus/Ordo',
    'Canellales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Laurales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Magnoliales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Piperales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Acorales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Alismatales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Arecales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Asparagales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Commelinales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Dioscoreales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Liliales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Pandanales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Petrosaviales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Poales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Zingiberales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Buxales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Ceratophyllales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Dilleniales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Gunnerales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Proteales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Ranunculales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Trochodendrales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Ordo',
    'Berberidopsidales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Caryophyllales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Santalales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Cornales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Ericales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Apiales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Aquifoliales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Asterales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Bruniales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Dipsacales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Escalloniales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Paracryphiales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Boraginales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Garryales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Gentianales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Icacinales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Lamiales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Metteniusales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Solanales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Vahliales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Saxifragales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Celastrales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Malpighiales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Oxalidales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Vitales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Cucurbitales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Fabales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Fagales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Rosales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Zygophyllales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Brassicales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Crossosomatales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Geraniales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Huerteales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Malvales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Myrtales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Picramniales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo',
    'Sapindales': 'Superregnum/Regnum/Cladus/Cladus/Cladus/Cladus/Cladus/Cladus/Ordo'
}

apgiv_values = {
    'Amborellales': 'Eukaryota/Plantae/Angiosperms/Basal angiosperms/Amborellales',
    'Austrobaileyales': 'Eukaryota/Plantae/Angiosperms/Basal angiosperms/Austrobaileyales',
    'Nymphaeales': 'Eukaryota/Plantae/Angiosperms/Basal angiosperms/Nymphaeales',
    'Canellales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Magnoliids/Canellales',
    'Laurales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Magnoliids/Laurales',
    'Magnoliales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Magnoliids/Magnoliales',
    'Piperales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Magnoliids/Piperales',
    'Acorales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Acorales',
    'Alismatales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Alismatales',
    'Arecales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Arecales',
    'Asparagales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Asparagales',
    'Commelinales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Commelinales',
    'Dioscoreales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Dioscoreales',
    'Liliales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Liliales',
    'Pandanales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Pandanales',
    'Petrosaviales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Petrosaviales',
    'Poales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Poales',
    'Zingiberales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Monocots/Zingiberales',
    'Buxales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Buxales',
    'Ceratophyllales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Ceratophyllales',
    'Dilleniales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Dilleniales',
    'Gunnerales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Gunnerales',
    'Proteales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Proteales',
    'Ranunculales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Ranunculales',
    'Trochodendrales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Trochodendrales',
    'Berberidopsidales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Berberidopsidales',
    'Caryophyllales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Caryophyllales',
    'Santalales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Santalales',
    'Cornales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Cornales',
    'Ericales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Ericales',
    'Apiales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Campanulids/Apiales',
    'Aquifoliales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Campanulids/Aquifoliales',
    'Asterales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Campanulids/Asterales',
    'Bruniales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Campanulids/Bruniales',
    'Dipsacales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Campanulids/Dipsacales',
    'Escalloniales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Campanulids/Escalloniales',
    'Paracryphiales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Campanulids/Paracryphiales',
    'Boraginales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Lamiids/Boraginales',
    'Garryales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Lamiids/Garryales',
    'Gentianales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Lamiids/Gentianales',
    'Icacinales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Lamiids/Icacinales',
    'Lamiales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Lamiids/Lamiales',
    'Metteniusales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Lamiids/Metteniusales',
    'Solanales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Lamiids/Solanales',
    'Vahliales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superasterids/Asterids/Lamiids/Vahliales',
    'Saxifragales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Saxifragales',
    'Celastrales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Celastrales',
    'Malpighiales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Malpighiales',
    'Oxalidales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Oxalidales',
    'Vitales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Vitales',
    'Cucurbitales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Fabids/Cucurbitales',
    'Fabales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Fabids/Fabales',
    'Fagales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Fabids/Fagales',
    'Rosales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Fabids/Rosales',
    'Zygophyllales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Fabids/Zygophyllales',
    'Brassicales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Malvids/Brassicales',
    'Crossosomatales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Malvids/Crossosomatales',
    'Geraniales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Malvids/Geraniales',
    'Huerteales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Malvids/Huerteales',
    'Malvales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Malvids/Malvales',
    'Myrtales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Malvids/Myrtales',
    'Picramniales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Malvids/Picramniales',
    'Sapindales': 'Eukaryota/Plantae/Angiosperms/Mesangiosperms/Eudicots/Superrosids/Rosids/Malvids/Sapindales'
}
