"""WCVP TDWG L3 → blank_world.css classes.

Grain of ingest/data/maps/blank_world.svg: ISO 3166-1 countries except
US states, Canadian provinces, Chinese provinces, and Russia as
ru-eu / ru-sib / ru-fe (WCVP L2 14 / 30 / 31).
"""

from __future__ import annotations

# L3 code → map class tokens. Empty tuple = no polygon (warn).
L3_TO_CLASSES: dict[str, tuple[str, ...]] = {
    # Northern Europe
    "DEN": ("dk",),
    "FIN": ("fi",),
    "FOR": ("fo",),
    "GRB": ("gb",),
    "ICE": ("is",),
    "IRE": ("ie",),
    "NOR": ("no",),
    "SVA": ("sj",),
    "SWE": ("se",),
    # Middle Europe
    "AUT": ("at",),
    "BGM": ("be",),
    "CZE": ("cz", "sk"),
    "GER": ("de",),
    "HUN": ("hu",),
    "NET": ("nl",),
    "POL": ("pl",),
    "SWI": ("ch",),
    # Southwestern Europe
    "BAL": ("es-bal",),
    "COR": ("fr",),
    "FRA": ("fr",),
    "POR": ("pt",),
    "SAR": ("it",),
    "SPA": ("es",),
    # Southeastern Europe
    "ALB": ("al",),
    "BUL": ("bg",),
    "GRC": ("gr",),
    "ITA": ("it",),
    "KRI": ("gr",),
    "ROM": ("ro",),
    "SIC": ("it",),
    "TUE": ("tr",),
    "YUG": ("ba", "hr", "me", "mk", "rs", "si"),
    # Eastern Europe
    "BLR": ("by",),
    "BLT": ("ee", "lv", "lt"),
    "KRY": ("xq",),  # Crimea polygon, not all of European Russia
    "RUC": ("ru-eu",),
    "RUE": ("ru-eu",),
    "RUN": ("ru-eu",),
    "RUS": ("ru-eu",),
    "RUW": ("ru-eu",),
    "UKR": ("ua",),
    # Northern Africa
    "ALG": ("dz",),
    "EGY": ("eg",),
    "LBY": ("ly",),
    "MOR": ("ma",),
    "TUN": ("tn",),
    "WSA": ("eh",),
    # Macaronesia
    "AZO": ("pt",),
    "CNY": ("es-cny",),
    "CVI": ("cv",),
    "MDR": ("pt",),
    "SEL": ("pt",),
    # West Tropical Africa
    "BEN": ("bj",),
    "BKN": ("bf",),
    "GAM": ("gm",),
    "GHA": ("gh",),
    "GNB": ("gw",),
    "GUI": ("gn",),
    "IVO": ("ci",),
    "LBR": ("lr",),
    "MLI": ("ml",),
    "MTN": ("mr",),
    "NGA": ("ng",),
    "NGR": ("ne",),
    "SEN": ("sn",),
    "SIE": ("sl",),
    "TOG": ("tg",),
    # West-Central Tropical Africa
    "BUR": ("bi",),
    "CAB": ("ao",),
    "CAF": ("cf",),
    "CMN": ("cm",),
    "CON": ("cg",),
    "EQG": ("gq",),
    "GAB": ("ga",),
    "GGI": ("st",),
    "RWA": ("rw",),
    "ZAI": ("cd",),
    # Northeast Tropical Africa
    "CHA": ("td",),
    "DJI": ("dj",),
    "ERI": ("er",),
    "ETH": ("et",),
    "SOC": ("so",),
    "SOM": ("so",),
    "SUD": ("sd",),
    # East / South Tropical / Southern Africa
    "KEN": ("ke",),
    "TAN": ("tz",),
    "UGA": ("ug",),
    "ANG": ("ao",),
    "MLW": ("mw",),
    "MOZ": ("mz",),
    "ZAM": ("zm",),
    "ZIM": ("zw",),
    "BOT": ("bw",),
    "CPP": ("za",),
    "CPV": ("na",),
    "LES": ("ls",),
    "NAM": ("na",),
    "NAT": ("za",),
    "OFS": ("za",),
    "SWZ": ("sz",),
    "TVL": ("za",),
    "ASC": ("sh",),
    "STH": ("sh",),
    "ALD": ("sc",),
    "CGS": ("io",),
    "COM": ("km",),
    "MAU": ("mu",),
    "MCI": ("mz",),
    "MDG": ("mg",),
    "REU": ("re",),
    "ROD": ("mu",),
    "SEY": ("sc",),
    # Siberia / Russian Far East
    "ALT": ("ru-sib",),
    "BRY": ("ru-sib",),
    "CTA": ("ru-sib",),
    "IRK": ("ru-sib",),
    "KRA": ("ru-sib",),
    "TVA": ("ru-sib",),
    "WSB": ("ru-sib",),
    "YAK": ("ru-sib",),
    "AMU": ("ru-fe",),
    "KAM": ("ru-fe",),
    "KHA": ("ru-fe",),
    "KUR": ("ru-fe",),
    "MAG": ("ru-fe",),
    "PRM": ("ru-fe",),
    "SAK": ("ru-fe",),
    # Middle Asia / Caucasus
    "KAZ": ("kz",),
    "KGZ": ("kg",),
    "TKM": ("tm",),
    "TZK": ("tj",),
    "UZB": ("uz",),
    "NCS": (),  # no separate polygon; rides with ru-eu
    "TCS": ("ge", "am", "az"),
    # Western Asia / Arabia
    "AFG": ("af",),
    "CYP": ("cy",),
    "EAI": ("gr",),
    "IRN": ("ir",),
    "IRQ": ("iq",),
    "LBS": ("lb", "sy"),
    "PAL": ("il", "jo"),
    "SIN": ("eg",),
    "TUR": ("tr",),
    "GST": ("ae", "bh", "qa"),
    "KUW": ("kw",),
    "OMA": ("om",),
    "SAU": ("sa",),
    "YEM": ("ye",),
    # China (WCVP L3 → CN provinces on the base)
    "CHC": ("cn-cq", "cn-gz", "cn-hb", "cn-sc", "cn-yn"),
    "CHH": ("cn-hi",),
    "CHI": ("cn-nm", "cn-nx"),
    "CHM": ("cn-hl", "cn-jl", "cn-ln"),
    "CHN": ("cn-bj", "cn-gs", "cn-he", "cn-sn", "cn-sd", "cn-sx", "cn-tj"),
    "CHQ": ("cn-qh",),
    "CHS": (
        "cn-ah",
        "cn-fj",
        "cn-gd",
        "cn-gx",
        "cn-ha",
        "cn-hn",
        "cn-js",
        "cn-jx",
        "cn-sh",
        "cn-zj",
    ),
    "CHT": ("cn-xz",),
    "CHX": ("cn-xj",),
    "MON": ("mn",),
    # Eastern Asia
    "JAP": ("jp",),
    "KOR": ("kp", "kr"),
    "KZN": ("jp",),
    "NNS": ("jp",),
    "OGA": ("jp",),
    "TAI": ("tw",),
    # Indian subcontinent / Indo-China / Malesia / Papuasia
    "ASS": ("in",),
    "BAN": ("bd",),
    "EHM": ("bt", "in"),
    "IND": ("in",),
    "LDV": ("in",),
    "MDV": ("mv",),
    "NEP": ("np",),
    "PAK": ("pk",),
    "SRL": ("lk",),
    "WHM": ("in",),
    "AND": ("in",),
    "CBD": ("kh",),
    "LAO": ("la",),
    "MYA": ("mm",),
    "NCB": ("in",),
    "SCS": ("cn-hi",),
    "THA": ("th",),
    "VIE": ("vn",),
    "BOR": ("bn", "id", "my"),
    "CKI": ("cc",),
    "JAW": ("id",),
    "LSI": ("id", "tl"),
    "MLY": ("my", "sg"),
    "MOL": ("id",),
    "PHI": ("ph",),
    "SUL": ("id",),
    "SUM": ("id",),
    "XMS": ("cx",),
    "BIS": ("pg",),
    "NWG": ("pg", "id"),
    "SOL": ("sb",),
    # Australasia
    "NFK": ("au",),
    "NSW": ("au",),
    "NTA": ("au",),
    "QLD": ("au",),
    "SOA": ("au",),
    "TAS": ("au",),
    "VIC": ("au",),
    "WAU": ("au",),
    "ATP": ("nz",),
    "CTM": ("nz",),
    "KER": ("nz",),
    "NZN": ("nz",),
    "NZS": ("nz",),
    # Pacific
    "FIJ": ("fj",),
    "GIL": ("ki",),
    "HBI": ("um",),
    "NRU": ("nr",),
    "NUE": ("nu",),
    "NWC": ("nc",),
    "PHX": ("ki",),
    "SAM": ("ws", "as"),
    "SCZ": ("sb",),
    "TOK": ("tk",),
    "TON": ("to",),
    "TUV": ("tv",),
    "VAN": ("vu",),
    "WAL": ("wf",),
    "COO": ("ck",),
    "EAS": ("cl",),
    "LIN": ("ki",),
    "MRQ": ("pf",),
    "PIT": ("pn",),
    "SCI": ("pf",),
    "TUA": ("pf",),
    "TUB": ("pf",),
    "CRL": ("fm", "pw"),
    "MCS": ("jp",),
    "MRN": ("gu", "mp"),
    "MRS": ("mh",),
    "WAK": ("um",),
    "HAW": ("us-hi",),
    # Subarctic / Canada / USA
    "ALU": ("us-ak",),
    "ASK": ("us-ak",),
    "GNL": ("gl",),
    "NUN": ("ca-nu",),
    "NWT": ("ca-nt",),
    "YUK": ("ca-yt",),
    "ABT": ("ca-ab",),
    "BRC": ("ca-bc",),
    "MAN": ("ca-mb",),
    "SAS": ("ca-sk",),
    "LAB": ("ca-nl",),
    "NBR": ("ca-nb",),
    "NFL": ("ca-nl",),
    "NSC": ("ca-ns",),
    "ONT": ("ca-on",),
    "PEI": ("ca-pe",),
    "QUE": ("ca-qc",),
    "COL": ("us-co",),
    "IDA": ("us-id",),
    "MNT": ("us-mt",),
    "ORE": ("us-or",),
    "WAS": ("us-wa",),
    "WYO": ("us-wy",),
    "ILL": ("us-il",),
    "IOW": ("us-ia",),
    "KAN": ("us-ks",),
    "MIN": ("us-mn",),
    "MSO": ("us-mo",),
    "NDA": ("us-nd",),
    "NEB": ("us-ne",),
    "OKL": ("us-ok",),
    "SDA": ("us-sd",),
    "WIS": ("us-wi",),
    "CNT": ("us-ct",),
    "INI": ("us-in",),
    "MAI": ("us-me",),
    "MAS": ("us-ma",),
    "MIC": ("us-mi",),
    "NWH": ("us-nh",),
    "NWJ": ("us-nj",),
    "NWY": ("us-ny",),
    "OHI": ("us-oh",),
    "PEN": ("us-pa",),
    "RHO": ("us-ri",),
    "VER": ("us-vt",),
    "WVA": ("us-wv",),
    "ARI": ("us-az",),
    "CAL": ("us-ca",),
    "NEV": ("us-nv",),
    "UTA": ("us-ut",),
    "NWM": ("us-nm",),
    "TEX": ("us-tx",),
    "ALA": ("us-al",),
    "ARK": ("us-ar",),
    "DEL": ("us-de",),
    "FLA": ("us-fl",),
    "GEO": ("us-ga",),
    "KTY": ("us-ky",),
    "LOU": ("us-la",),
    "MRY": ("us-md",),
    "MSI": ("us-ms",),
    "NCA": ("us-nc",),
    "SCA": ("us-sc",),
    "TEN": ("us-tn",),
    "VRG": ("us-va",),
    "WDC": ("us-dc",),
    # Mexico (country grain on this base)
    "MXC": ("mx",),
    "MXE": ("mx",),
    "MXG": ("mx",),
    "MXI": ("mx",),
    "MXN": ("mx",),
    "MXS": ("mx",),
    "MXT": ("mx",),
    # Central America / Caribbean
    "BLZ": ("bz",),
    "COS": ("cr",),
    "CPI": ("cr",),
    "ELS": ("sv",),
    "GUA": ("gt",),
    "HON": ("hn",),
    "NIC": ("ni",),
    "PAN": ("pa",),
    "ARU": ("aw",),
    "BAH": ("bs",),
    "BER": ("bm",),
    "CAY": ("ky",),
    "CUB": ("cu",),
    "DOM": ("do",),
    "HAI": ("ht",),
    "JAM": ("jm",),
    "LEE": ("ag", "kn", "vg"),
    "NLA": ("cw", "bq"),
    "PUE": ("pr",),
    "SWC": ("co", "hn", "ni"),
    "TCI": ("tc",),
    "TRT": ("tt",),
    "VNA": ("ve",),
    "WIN": ("bb", "gd", "lc", "vc"),
    # South America
    "FRG": ("gf",),
    "GUY": ("gy",),
    "SUR": ("sr",),
    "VEN": ("ve",),
    "BOL": ("bo",),
    "CLM": ("co",),
    "ECU": ("ec",),
    "GAL": ("ec",),
    "PER": ("pe",),
    "BZC": ("br",),
    "BZE": ("br",),
    "BZL": ("br",),
    "BZN": ("br",),
    "BZS": ("br",),
    "AGE": ("ar",),
    "AGS": ("ar",),
    "AGW": ("ar",),
    "CLC": ("cl",),
    "CLN": ("cl",),
    "CLS": ("cl",),
    "DSV": ("cl",),
    "JNF": ("cl",),
    "PAR": ("py",),
    "URU": ("uy",),
    # Antarctic
    "ASP": ("tf",),
    "BOU": ("bv",),
    "CRZ": ("tf",),
    "FAL": ("fk",),
    "HMD": ("hm",),
    "KEG": ("tf",),
    "MAQ": ("au",),
    "MPE": ("za",),
    "SGE": ("gs",),
    "SSA": ("gs",),
    "TDC": ("sh",),
    "ANT": ("aq",),
}


def classes_for_l3(codes: list[str]) -> tuple[list[str], list[str]]:
    """Return (map classes, unmapped L3 codes)."""
    out: list[str] = []
    missing: list[str] = []
    seen: set[str] = set()
    for raw in codes:
        code = str(raw or "").strip().upper()
        if not code:
            continue
        if code not in L3_TO_CLASSES:
            missing.append(code)
            continue
        mapped = L3_TO_CLASSES[code]
        if not mapped:
            missing.append(code)
            continue
        for token in mapped:
            if token not in seen:
                seen.add(token)
                out.append(token)
    return out, missing
